name: best_price
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.5.4"

dependencies:
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.2+1
  expandable_text: ^2.3.0
  top_snackbar_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_html: ^3.0.0-beta.2
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  get_it: ^7.6.7
  intl:
  logger: ^2.1.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences:
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.1
  chewie: ^1.10.0
  video_player: ^2.9.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash/
    - assets/images/onBoarding/
    - assets/images/home/
    - assets/icons/

  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans/JosefinSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans/JosefinSans-SemiBold.ttf
          weight: 600

flutter_intl:
  enabled: true
